Add WP_CLI command interface.
wp-oop/wordpress-interface pull request #2
Opened 2020-07-26 06:43 UTC by strangerkir

This PR is made to add the WP_CLI command interface. Ideas for the interface is taken from [this comment](https://github.com/inpsyde/idealo-cli-command/pull/1#discussion_r458646181).

I also added tests in the same way it was done for the existing interfaces. I have doubts if they are useful in this case, but I did it at least for consistency.

2020-07-29 08:00 UTC, XedinUnknown requested changes

2020-07-29 08:00 UTC, XedinUnknown commented on src/WpCli/WpCliCommandInterface.php
> +}
EOL missing

2020-07-29 08:00 UTC, XedinUnknown commented on src/WpCli/WpCliCommandInterface.php
> + * Represents WP_CLI command.
```suggestion
 * Represents a WP_CLI command.
```

2020-07-29 08:00 UTC, XedinUnknown commented on tests/unit/WpCli/WpCliCommandInterfaceTest.php
> +}
EOL

2020-07-30 07:14 UTC, strangerkir commented on src/WpCli/WpCliCommandInterface.php
> +}
Fixed.

2020-07-30 07:14 UTC, strangerkir commented on tests/unit/WpCli/WpCliCommandInterfaceTest.php
> +}
Fixed.

2021-03-05 17:15 UTC, closed without merging